### ISSUE TITLE
Error with Pyro version 1.9.0

### ISSUE THREAD

**Issue by devonjkohler** [BasisResearch/chirho#538]
Hello,

I've noticed an error when running the package with the newest version of Pyro.

Importing `chirho.interventional.handlers.do` returns the following error:

`Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/root/miniconda3/envs/py311/lib/python3.11/site-packages/chirho/interventional/__init__.py", line 1, in <module>        from . import handlers  # noqa: F401
^^^^^^^^^^^^^^^^^^^^^^
File "/root/miniconda3/envs/py311/lib/python3.11/site-packages/chirho/interventional/handlers.py", line 121, in <module>      
do = pyro.poutine.handlers._make_handler(Interventions)[1]  `

Rolling this back to Pyro 1.8 fixes this issue.

**Comment by SamWitty** [comment]
Hello @devonjkohler. Thanks for your interest in ChiRho, and for pointing out the compatibility issue. 

This is a known issue, and will be addressed very soon when we cut a release including #518 . In fact, #537 brought up the same issue. We've pinned the pyro version in the `setup.py` file here: https://github.com/BasisResearch/chirho/blob/master/setup.py#L44.

I'll leave this issue up until we cut the next release, as others are likely to encounter the same compatibility issue.

**Comment by jfeser** [comment]
Fixed by releasing 0.3.0.
